### ISSUE TITLE
BAML tests stoped working

### ISSUE THREAD

**Issue by MindsightsAI** [BoundaryML/baml#1272]
Problem started today. Other openai requests from same ide with same key works fine.

Playground webview devtools console log:
```
workbench.desktop.main.js:3530 [Extension Host] proxy error: Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:218:20)
workbench.desktop.main.js:3530 [Extension Host] [HPM] Error occurred while proxying request localhost:45150/chat/completions to https://api.openai.com/v1 [ECONNRESET] (https://nodejs.org/api/errors.html#errors_common_system_errors)
baml_schema_build.js:3226 Uncaught Error: recursive use of an object detected which would lead to unsafe aliasing in rust
    at __wbindgen_throw (baml_schema_build.js:3226:11)
    at baml_schema_build.wasm.wasm_bindgen::throw_str::h91abd0c96c9b1ae1 (baml_schema_build.wasm-02a961ee:0x7efb70)
    at baml_schema_build.wasm.wasm_bindgen::__rt::borrow_fail::ha584e99bb8926828 (baml_schema_build.wasm-02a961ee:0x7efb8e)
    at baml_schema_build.wasm.wasmruntime_get_function_at_position (baml_schema_build.wasm-02a961ee:0x73081b)
    at WasmRuntime.get_function_at_position (baml_schema_build.js:2245:26)
    at Object.write (index.mjs:145:33)
    at writeAtomState (children.js:45:1)
    at Object.writeAtom [as set] (children.js:50:16)
    at di.js:163:22
    at fn (index.mjs:138:7)

```

Language server log:
```log
Initialized BAML runtime logging as log::WARN
cant load webcrypto TypeError: Cannot set property crypto of #<Object> which has only a getter
    at src/server.ts (/home/m/.cursor-server/extensions/boundary.baml-extension-0.70.5/language-server/out/bin.js:18521:25)
    at __init (/home/m/.cursor-server/extensions/boundary.baml-extension-0.70.5/language-server/out/bin.js:10:56)
    at src/cli.ts (/home/m/.cursor-server/extensions/boundary.baml-extension-0.70.5/language-server/out/bin.js:18536:5)
    at __init (/home/m/.cursor-server/extensions/boundary.baml-extension-0.70.5/language-server/out/bin.js:10:56)
    at Object.<anonymous> (/home/m/.cursor-server/extensions/boundary.baml-extension-0.70.5/language-server/out/bin.js:18542:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
Server-side -- startServer()
Starting Baml Language Server...
Server-side -- listening to connection
[Info  - 5:49:46 PM] Extension 'baml-extension': 0.70.5
initialized
Upserting file: file:///home/m/hsl/baml_src/hsl_agent.baml. current projects  0  {}
configResponse {
  "cliPath": null,
  "generateCodeOnSave": "always",
  "restartTSServerOnSave": false,
  "enablePlaygroundProxy": true,
  "fileWatcher": false,
  "trace": {
    "server": "off"
  },
  "bamlPanelOpen": true
}
projects 0: {},
projects 1: {},
Error sending runtime_diagnostics: Error: Unhandled method runtime_diagnostics
Error sending runtime_updated: Error: Unhandled method runtime_updated
Error sending runtime_diagnostics: Error: Unhandled method runtime_diagnostics
Error sending runtime_updated: Error: Unhandled method runtime_updated

```

**Comment by MindsightsAI** [comment]
BAML extension setting to disable proxy helps me!
