### ISSUE TITLE
Error will running Quickstart demo code.

### ISSUE THREAD

**Issue by Sidd065** [BoundaryML/baml#894]
After running `baml-cli init` and `baml-cli generate`, I added azure-openai provider to `clients.baml` and ran the example code.
```python
from baml_client.sync_client import b
from baml_client.types import Resume

def example(raw_resume: str) -> Resume: 
  # BAML's internal parser guarantees ExtractResume
  # to be always return a Resume type
  response = b.ExtractResume(raw_resume)
  return response

def example_stream(raw_resume: str) -> Resume:
  stream = b.stream.ExtractResume(raw_resume)
  for msg in stream:
    print(msg) # This will be a PartialResume type
  
  # This will be a Resume type
  final = stream.get_final_response()

  return final

resume_text = """Jason Doe
Python, Rust
University of California, Berkeley, B.S.
in Computer Science, 2020
Also an expert in Tableau, SQL, and C++
"""
example(resume_text)
```
Running the above code gives me this error.
```bash
Traceback (most recent call last):
  File "/home/sidd065/test/testBAML.py", line 28, in <module>
    example(resume_text)
  File "/home/sidd065/test/testBAML.py", line 9, in example
    response = b.ExtractResume(raw_resume)
  File "/home/sidd065/test/baml_client/sync_client.py", line 82, in ExtractResume
    return coerce(mdl, raw.parsed())
  File "/home/sidd065/test/baml_client/sync_client.py", line 31, in coerce
    return cls.model_validate({"inner": parsed}).inner # type: ignore
AttributeError: type object 'ExtractResumeReturnType' has no attribute 'model_validate'
```

**Comment by Sidd065** [comment]
I was using pydantic 1.xx, upgrading to pydantic 2.0+ fixed the issue
